ARG version
FROM almalinux:${version}
ARG mobile
ARG laptop
RUN echo "mobile is ${mobile} laptop is ${laptop} "
CMD [ "sleep" , "100" ]











# How can you check the version of your server OS? cat /etc/*release