ARG version
FROM almalinux:${version:-8.6}
ARG mobile=Nokia
ARG laptop=HCL
ARG TV=LG
ENV TV=${TV}}
RUN echo "mobile is ${mobile} laptop is ${laptop} TV is ${TV} "
CMD [ "sleep" , "100" ]











# How can you check the version of your server OS? cat /etc/*release